### ISSUE TITLE
[Bug]: Able to go on trees/ objects which have a slope + some ladders

### ISSUE THREAD

**Issue by Shadewarezx** [CompilerErrorRBX/Quarantine-Aftermath#29]
### What happened?

When ever running if I run into a tree that has a slope I can climb it + hangars it on the airfield the slopes increase the speed of your running.
(cannot upload video due to size)

**Comment by DarrenLam2** [comment]
Any steep slope will trigger this effect.

**Comment by CompilerErrorRBX** [comment]
Pretty sure this issue is fixed during this weekend test? Is that not the case?

**Comment by DarrenLam2** [comment]
For the most part it seemed fixed over the weekend. I will test later today to confirm.

**Comment by DarrenLam2** [comment]
Seems to be completely fixed. Characters still seem to stutter a tiny bit, but it won't cause any significant issues.
