### ISSUE TITLE
Visual Bug: Scrapping worn items does not remove inventory panel

### ISSUE THREAD

**Issue by DarrenLam2** [CompilerErrorRBX/Quarantine-Aftermath#42]
### What happened?

Scrapped duffle bag + pants while wearing
![image](https://github.com/CompilerErrorRBX/Quarantine-Aftermath/assets/158836510/668b0665-2ddb-4f41-9651-f7527dbd2a8b)

**Comment by CompilerErrorRBX** [comment]
This should be fixed.
