### ISSUE TITLE
Unable to load sound

### ISSUE THREAD

**Issue by DarrenLam2** [CompilerErrorRBX/Quarantine-Aftermath#44]
### What happened?

![image](https://github.com/CompilerErrorRBX/Quarantine-Aftermath/assets/158836510/6c00ddfe-2187-420c-b34d-0a7608b4f017)
No audio from any source in the game.
Only fixed when rejoining.

**Comment by CompilerErrorRBX** [comment]
Unfortunately, this is an issue with Roblox and we actually cannot do anything about it. It will never try to reload those sounds until you rejoin.
