### ISSUE TITLE
Scrapping equipped items does not remove its status effects

### ISSUE THREAD

**Issue by DarrenLam2** [CompilerErrorRBX/Quarantine-Aftermath#49]
### What happened?

If you have a hazmat piece equipped or armor equipped, scrapping it while wearing it will keep the status effects, while removing the need for durability. This allows you to have permanent helmets (as long as you stay in the server) and infinite radiation protection with tactical clothing.

**Comment by CompilerErrorRBX** [comment]
This issue should be fixed now.

**Comment by DarrenLam2** [comment]
Was fixed last time I tested.
