### ISSUE TITLE
[Bug]: Crafting Bug Items Going into The Negatives

### ISSUE THREAD

**Issue by HunterHanz** [CompilerErrorRBX/Quarantine-Aftermath#50]
### What happened?

So I have had this happen to me 2 times one time while i was crafting Tape i was able to start crafting fiber with the resources i had even tho the Tape wasent Finished Crafting So i clicked Craft Fiber it then started crafting fiber but when the Tape got Finished Crafting it stoped crafting the FIber and then it said 0/1 Fiber i then Dropped The Tape which it then said -1/1 So i needed 2 tapes to craft 1 Fiber But the Resouce Intake was still the same so i needed 2 Tapes but only 1 was taken .

Second Time the Item i was gonna craft was a Large Medkit i then dropped the tape on accident while i was crafting the Medkit then i picked it up and it said 2/4 even ths i had 4 Tapes i then dropped the Tapes again and it said -2/4 the intake was still the same but i needed more tape to even be able to craft it.

**Comment by DarrenLam2** [comment]
I don't have spawn perms anymore so I can't test everything, so I can't test everything, so I'll just leave it off with 1 reproduction method.

If you interrupt a craft by scrapping or dropping the clothing item your materials are in, it will display your material count as -[material amount that you dropped], allowing you to get incorrect quantities.

**Comment by CompilerErrorRBX** [comment]
I believe this issue is fixed. A new issue was created with crafting where it breaks but I don't think you'll have this problem anymore.
