### ISSUE TITLE
[Bug]: Uzi is in your body but supposed to be at the back when it is unequipped.

### ISSUE THREAD

**Issue by Shadewarezx** [CompilerErrorRBX/Quarantine-Aftermath#52]
### What happened?

![Desktop Screenshot 2024 02 24 - 11 30 59 33](https://github.com/CompilerErrorRBX/Quarantine-Aftermath/assets/159146292/91ea5df8-932e-4a14-b750-70206a206248)
Yes so when unequipped the Uzi is your right arm.

**Comment by CompilerErrorRBX** [comment]
This is intentional.
