### ISSUE TITLE
[Bug]: Ping bug 

### ISSUE THREAD

**Issue by Shadewarezx** [CompilerErrorRBX/Quarantine-Aftermath#59]
### What happened?

I ended up dying as I pinged and then the ping would be stuck at 815 meters I don't know why but my friend was experiencing it too but at a different number
![Uploading Roblox VR Screenshot 2024.03.06 - 19.10.03.96.png…]()

**Comment by CompilerErrorRBX** [comment]
Image doesn't work.

**Comment by CompilerErrorRBX** [comment]
I believe this issue will be fixed in game version 382.
