### ISSUE TITLE
[Bug]: Flying house a lil above almosta town

### ISSUE THREAD

**Issue by realspaceyy** [CompilerErrorRBX/Quarantine-Aftermath#61]
### What happened?

![d3b51cd48236dc00488de01b7fff0d85](https://github.com/CompilerErrorRBX/Aftermath/assets/163068184/a8fbce47-2185-41da-a2b1-1968ba4c4bad)

**Comment by realspaceyy** [comment]
location, a lil above almosta town

**Comment by CompilerErrorRBX** [comment]
We've fixed this a few days ago, but we haven't updated the map yet. Should be fixed in the next few days. Thanks for the report!
